  on:
    push:
      branches:
        - master




  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/chechout@v3
        - name: 'printings content'
          run: ls

